version : '3.8'
services:
  db: 
    container_name: roullet_robot
    image: postgres:11.6-alpine
    restart: always
    command: postgres -c logging_collector=on -c log_destination=stderr 
    environment:
      - POSTGRES_USER=roullet
      - POSTGRES_PASSWORD=roullet
      - POSTGRES_DB=roullet
      - POSTGRES_HOST=localhost
      - POSTGRES_INITDB_ARGS=--locale=en_US.UTF-8
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore
    
    ports:
      - "5532:5432"
  redisDb: 
    container_name: roullet_redis
    image: redis:5.0.5-alpine
    restart: always
    command: redis-server --appendonly yes --requirepass roullet
    ports:
      - "6379:6379"
  RabbitMQ:
    container_name: roullet_rabbitmq
    image: rabbitmq:3.7.8-management
    restart: always
    command: rabbitmq-plugins enable rabbitmq_management
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=roullet
      - RABBITMQ_DEFAULT_PASS=roullet
        
